#!/bin/bash
#
# <org-bash-blog v5 . Build a blog from a single orgmode file with pandoc and all the bash power>
#
# Copyright (C) 2019 Angel. uGeek
# ugeekpodcast@gmail.com
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#
#

source config
if [ $1 = "-h" ]
then
echo "

Modo de empleo:     ./org-bash-blog [ARCHIVO ORG-MODE] 

       Comando                      Significado
       ./org-bash-blog -h           Ayuda
       ./org-bash-blog -b           Construir carpetas
       ./org-bash-blog -n           Nuevo Post
       ./org-bash-blog -f           Crear Nuevo Org-Mode



Ejemplos:

./org-bash-blog -n [ARCHIVO ORG-MODE] 'Título del Artículo'
./org-bash-blog -f [ARCHIVO ORG-MODE] 

"
else  
if [ $1 = "-b" ]
then
mkdir -p icon css org post images-blog
else  
if [ $1 = "-n" ]
then
echo "Creada Nueva Entrada"
DIA=$(date +"%Y-%m-%d %H:%M")
echo '* TODO '$3'
:PROPERTIES:
:TITLE: '$3'
:EXPORT_FILE_NAME: '$3'
:DESCRIPTION:
:EXPORT_DATE: '$DIA'
:CATEGORY:
:TAG:
:IMAGE:
:END:
' >> $2
$EMACS $2
else  
if [ $1 = "-f" ]
then
echo "
#+TITLE:
#+LINK:
#+DESCRIPTION:
#+KEYWORDS:
#+AUTHOR:

 " > $2
else      
TITLE=$(grep "#+TITLE:" $1 | cut -d " " -f2-)
LINK=$(grep "#+LINK:" $1 | cut -d " " -f2-)
DESCRIPTION=$(grep "#+DESCRIPTION:" $1 | cut -d " " -f2-)
AUTHOR=$(grep "#+AUTHOR:" $1 | cut -d " " -f2-)
grep ":TITLE:" $1 | cut -d " " -f2- | sed 's/,/|/g' > title
grep ":EXPORT_FILE_NAME:" $1 | cut -d " " -f2- | sed 's/ /-/g' | awk '{print tolower($0)}' > link
grep ":DESCRIPTION:" $1 | cut -d " " -f2- | sed 's/,/|/g'> description 
grep ":EXPORT_DATE:"  $1 | cut -d " " -f2 > date-
grep ":EXPORT_DATE:"  $1 | cut -d " " -f3 > hour
grep ":CATEGORY:"  $1 | cut -d " " -f2- > category
grep ":TAG:" $1 | cut -d " " -f2- | tr -d ' ' | sed "s|$|,,,,,,,,,|" | cut -d, -f -10 > tag
grep ":IMAGE:" $1 | cut -d " " -f2- | tr -d ' ' > image
cat date- |  tr -d '-' > date
paste -d, date title link description date- category tag hour image > postsID.csv
cat postsID.csv | sort -r | cut -d, -f2- > posts.csv
cat postsID.csv | sort | cut -d, -f2- > posts4feed.csv
cat posts.csv | cut -d "," -f5 | sed '/^ *$/d' | uniq | sort > category.csv
cat tag | cut -d "," -f1 > tags.csv
cat tag | cut -d "," -f2 >> tags.csv 
cat tag | cut -d "," -f3 >> tags.csv
cat tag | cut -d "," -f4 >> tags.csv
cat tag | cut -d "," -f5 >> tags.csv
cat tag | cut -d "," -f6 >> tags.csv
cat tag | cut -d "," -f7 >> tags.csv
cat tag | cut -d "," -f8 >> tags.csv
cat tag | cut -d "," -f9 >> tags.csv
cat tag | cut -d "," -f10 >> tags.csv
cat tags.csv | sed '/^ *$/d' | sort | uniq > tag.csv
echo " " >> $1
NUM_POSTS=$(cat posts.csv |  wc -l)
TODO=$(grep -irq "^* TODO" $1)
if [ $? -eq 0 ]; then
clear
echo ">>> org-bash-blog va a publicar el Post <<<"
grep -n "^* TODO" $1 |  cut -d ":" -f1 > TODO.txt
LINES_BLOG=$(cat $1  | wc -l)
cat $1  | wc -l >> TODO.txt
echo "Hay $NUM_POSTS Artículos y $LINES_BLOG líneas en $1"
echo "Se va a publicar $(grep -n "^* TODO" $1 | wc -l) Artículos"
rm org/*.org
ONE_LINE=$(cat TODO.txt | head -1)
sed -i '1d' TODO.txt
while read TWO_LINE; do
LAST_LINE=$(($TWO_LINE - 1))
CATEGORY=$(cat $1 | sed -n  "$ONE_LINE,$LAST_LINE"p | sed 's/* TODO/*/g' | grep ":CATEGORY:"  | cut -d " " -f2)
cat $1 | sed -n  "$ONE_LINE,$LAST_LINE"p | sed 's/* TODO/*/g' >> org/$CATEGORY.org
cat $1 | sed -n  "$ONE_LINE,$LAST_LINE"p | sed 's/* TODO/*/g' > temp_post.org
ONE_LINE=$(echo $TWO_LINE)
PUB=$(expr $PUB + 1)
echo "Publicando Artículo Nº $PUB     $(grep ":TITLE:" temp_post.org | cut -d " " -f2-)"
FILE_DATE=$(grep ":EXPORT_DATE:" temp_post.org | cut -d " " -f2)
DATE_MOD=$(grep ":EXPORT_DATE:" temp_post.org | cut -d " " -f4)
if [ -n "$DATE_MOD" ];
then
    echo "               ***** Artículo Modificado *****"
    UPDATE=$(echo " y *actualizado* el $(date -d"$DATE_MOD" +'%A %d %B del %Y')")
fi
echo "#+HTML: <br>" >> temp_post.org
echo "Publicado por $AUTHOR el $(date -d"$FILE_DATE" +'%A %d %B del %Y') $UPDATE" >> temp_post.org
UPDATE=$(echo " ")
echo "#+HTML: <br><br> " >> temp_post.org
echo "También te puede interesar:
 "  >> temp_post.org
CATEGORY=$(grep ":CATEGORY:" temp_post.org | cut -d " " -f2)
grep -i $CATEGORY posts.csv | sed '1d' > category_temp_post.csv
cat category_temp_post.csv | head -n10 > cat_temp.csv
cp cat_temp.csv category_temp_post.csv
while read LINEA; do  
OTHERSTITLE=$(echo $LINEA | cut -d, -f1 | sed 's/|/,/g')
OTHERSLINKS=$(echo $LINEA | cut -d, -f2)
OTHERSDATE=$(echo  $LINEA | cut -d, -f4)
echo "- [[$LINK/post/$OTHERSDATE-$OTHERSLINKS.html][$OTHERSTITLE]]" >> temp_post.org
done < category_temp_post.csv
FILE_TITLE=$(grep ":TITLE:" temp_post.org | cut -d " " -f2- | sed 's/|/,/g')
FILE_NAME=$(grep ":EXPORT_FILE_NAME:" temp_post.org | cut -d " " -f2- |awk '{print tolower($0)}' |  sed 's/ /-/g')
FILE_DATE=$(grep ":EXPORT_DATE:" temp_post.org | cut -d " " -f2)
FILE_IMAGE=$(grep ":IMAGE:" temp_post.org  | cut -d " " -f2- | sed 's|./images-blog/||g' | sed 's/ //g' )
FILE=$(echo "$FILE_DATE-$FILE_NAME")
FILE_DESCRIPTION=$(grep ":DESCRIPTION:" temp_post.org | cut -d " " -f2-)
DESCRIPTION_P=$(echo $FILE_DESCRIPTION | sed 's/|/,/g')
sed -i "1i #+DESCRIPTION: $DESCRIPTION_P" temp_post.org
FILE_TAG=$(grep ":TAG:" temp_post.org | cut -d " " -f2-)
TAG=$(echo $FILE_TAG | sed 's/|/,/g')
sed -i "1i #+KEYWORDS: $TAG" temp_post.org
echo "#+TITLE: $FILE_TITLE" > $FILE.org
cat temp_post.org >> $FILE.org
echo '<head>
<title>'$FILE_TITLE'. '$TITLE'</title>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<div id="logo"><a href="https://ugeek.github.io"><img src="../icon/ugeek.png" border="0"  width="90" height="90" alt="uGeek"></a></div>
<link rel="stylesheet" type="text/css" href="../css/stylesheet.css" />
<link rel="alternate" type="application/rss+xml" href="'$LINK'/feed.xml" title="uGeek - Blog de Tecnología">

<link rel="shortcut icon" href="'$LINK$ICON'" type="image/x-icon" />
<link rel="icon" href="'$LINK$ICON'" sizes="32x32" />
<link rel="icon" href="'$LINK$ICON'" sizes="192x192" />
<link rel="apple-touch-icon-precomposed" href="'$LINK$ICON'" />
<meta property="og:locale" content="'$LANGUAGE'" />



<meta name="robots" content="index, follow">
<meta name="twitter:site" content="'$TWITTER'" />
<meta name="twitter:card" content="summary_large_image" />
<link rel="alternate" type="application/rss+xml" title="uGeek. Blog de Tecnología" href="'$LINK'/feed/" />


<meta name="author" content="'$AUTHOR'">
<meta name="description" content="'$FILE_DESCRIPTION'" />


<meta property="og:site_name" content="'$TITLE'"/>
<meta property="og:type" content="article" /> 
<meta property="og:title" content="'$FILE_TITLE'" />
<meta property="og:description" content="'$FILE_DESCRIPTION'" />
<meta property="og:image" content="'$LINK'/images-blog/'$FILE_IMAGE'" />
<meta property="og:url" content="'$LINK'/post/'$FILE'.html" />

<meta name="twitter:title" content="'$FILE_TITLE'" />
<meta name="twitter:description" content="'$FILE_DESCRIPTION'" />
<meta name="twitter:image" content="'$LINK'/images-blog/'$FILE_IMAGE'" />


<link rel="stylesheet" type="text/css" href="css/stylesheet.css" /><link rel="alternate" type="application/rss+xml" href="https://ugeek.github.io/feed.xml" title="uGeek - Blog de Tecnología">

<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id='$GOOGLE_ANALITYCS'"></script>
<script>
window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag("'js'", new Date())
gtag("'config'", "'$GOOGLE_ANALITYCS'");
</script>

</head>

<br><br><br><br><br><br><br><br><br>

'$HEAD_PAGE_POST'
' >   $FILE.html
cat $FILE.org | pandoc --from org --to html5 >> $FILE.html
ORG=$(echo '<br><br><br><p style="text-align: center;">Powered by <a href="https://github.com/ugeek/org-bash-blog" target="_blank" rel="noopener">org-bash-blog</a></p><p style="text-align: center;">Writing in orgmode whith emacs</p>')
echo $ORG $PIE_WEB  >> $FILE.html
rm $FILE.org
sed -i 's|src="./images-blog/|src="../images-blog/|g' $FILE.html
sed -i 's|__icon/|../icon/|g' $FILE.html
sed -i 's|href="__css/|href="..css/|g' $FILE.html
sed -i 's|href="index.html"|href="../index.html"|g' $FILE.html
sed -i 's|href="list.html"|./href="../list.html"|g' $FILE.html
sed -i 's|href="tag.html"|./href="../tag.html"|g' $FILE.html
mv $FILE.html post/$FILE.html
done < TODO.txt
rm TODO.txt
echo '<html>
<html lang="es"><head><meta charset="utf-8"><meta name="robots" content="noindex">
<title>org-bash-blog. Index</title>
<link rel="stylesheet" type="text/css" href="./css/stylesheet.css" />
</head>
<body>
<h1>Org-bash-blog v 5.0</h1>
<h3>Indice de todas las páginas creadas en tu repositorio</h3>
<h5>'$(find . -type f | grep .html | wc -l)' archivos .html</h5>
<h5>' > org-bash-blog.html
find . -type f | grep .html | sed -r 's/(.*)/\<a href="\1" target="_blank" rel="noopener">\1\<\/a\><br>/' | sort -r >> org-bash-blog.html
$BROWSER org-bash-blog.html 
$BROWSER "post/$FILE.html" 
clear
echo "Generando Feed"
TODAY=$(date +'%A %d de %B del %Y')
echo '<?xml version="1.0" encoding="utf-8"?>
<rss xmlns:atom="http://www.w3.org/2005/Atom" version="2.0">
  <channel>
    <title>'$TITLE'</title>
    <link>'$LINK'</link>
    <description>'$DESCRIPTION'</description>
    <image>
       <url>'$LOGO_FEED'</url>
       <title>'$TITLE'</title>
       <link>'$LINK'</link>
    </image>
    <language>'$LANGUAGE_RSS'</language>
    <atom:link href="'$LINK'/feed.xml" rel="self" type="application/rss+xml" />
    <generator>org-bash-blog static site generator (https://github.com/ugeek/org-bash-blog)</generator>'> feed.xml
while read LINEA; do 
TITLE_F="$(echo $LINEA | cut -d, -f1 | sed 's/|/,/g')"
LINK_P="$(echo $LINEA | cut -d, -f2)"
DESC="$(echo $LINEA | cut -d, -f3 | sed 's/|/,/g')"
CATEGORY_POST="$(echo $LINEA | cut -d, -f5)"
CATEGORY_POST1="$(echo $LINEA | cut -d, -f6)"
CATEGORY_POST2="$(echo $LINEA | cut -d, -f7)"
CATEGORY_POST3="$(echo $LINEA | cut -d, -f8)"
IMAGE_POST="$(echo $LINEA | cut -d, -f17 | sed "s|^./|$LINK/|")"
DATE="$(echo $LINEA | cut -d, -f4)"
HORA="$(echo $LINEA | cut -d, -f16)"
DATEPU="$(LANG=en_us_88591 ; date -d"$DATE" +'%a, %d %b %Y')"
DATEPUB=$(echo "$DATEPU $HORA +0100")
LANG=locale
GUID="http://ugeek.github.io"
echo "   <item>" >> feed.xml
echo "    <title>$TITLE_F</title>" >> feed.xml
echo "    <link>$LINK/post/$DATE-$LINK_P.html</link>" >> feed.xml
echo "    <description>" >> feed.xml
echo '&lt;img src="'$IMAGE_POST'" alt="'$TITLE_F'"&gt;'   >> feed.xml
echo "&lt;br&gt;&lt;p&gt;$DESC... 
&lt;p&gt;Sigue leyendo el post completo de &lt;a href="$LINK/post/$DATE-$LINK_P.html"&gt;$TITLE_F&lt;/a&gt;

&lt;/a&gt;&lt;/p&gt;&lt;p&gt;

&lt;a href="$LINK"&gt;Visita $TITLE&lt;/a&gt;

&lt;/a&gt;&lt;/p&gt;&lt;p&gt;

&lt;a href="https://ugeek.github.io"&gt;Visita uGeek Podcast&lt;/a&gt;


&lt;/a&gt;&lt;/p&gt;&lt;p&gt;

&lt;a href="http://feeds.feedburner.com/ugeekblog"&gt;Suscribete al Blog de uGeek&lt;/a&gt;

&lt;/a&gt;&lt;/p&gt;&lt;p&gt;

&lt;a href="http://feeds.feedburner.com/ugeek"&gt;Suscribete al Podcast de uGeek&lt;/a&gt;

</description>" >> feed.xml
echo "    <pubDate>$DATEPUB</pubDate>" >> feed.xml
echo '    <category>'$CATEGORY_POST'</category>'  >> feed.xml
echo '    <category>'$CATEGORY_POST1'</category>'  >> feed.xml
echo '    <category>'$CATEGORY_POST2'</category>'  >> feed.xml
echo '    <category>'$CATEGORY_POST3'</category>'  >> feed.xml
echo "    <guid>$LINK/post/$DATE-$LINK_P.html</guid>
   </item>" >> feed.xml
done < posts.csv
echo "  </channel>
</rss>" >> feed.xml
echo "Generando Feed por Categoría"
WORD="emacs"
awk '/,emacs,/ { print }' posts.csv > emacs.csv
echo '<?xml version="1.0" encoding="utf-8"?>
<rss xmlns:atom="http://www.w3.org/2005/Atom" version="2.0">
  <channel>
    <title>'$TITLE'</title>
    <link>'$LINK'</link>
    <description>'$DESCRIPTION'</description>
    <image>
       <url>'$LOGO_FEED'</url>
       <title>'$TITLE'</title>
       <link>'$LINK'</link>
    </image>
    <language>'$LANGUAGE_RSS'</language>
    <atom:link href="'$LINK'/feed.xml" rel="self" type="application/rss+xml" />
    <generator>org-bash-blog static site generator (https://github.com/ugeek/org-bash-blog)</generator>'> $WORD.xml
while read LINEA; do 
TITLE_F="$(echo $LINEA | cut -d, -f1 | sed 's/|/,/g')"
LINK_P="$(echo $LINEA | cut -d, -f2)"
DESC="$(echo $LINEA | cut -d, -f3 | sed 's/|/,/g')"
CATEGORY_POST="$(echo $LINEA | cut -d, -f5)"
CATEGORY_POST1="$(echo $LINEA | cut -d, -f6)"
CATEGORY_POST2="$(echo $LINEA | cut -d, -f7)"
CATEGORY_POST3="$(echo $LINEA | cut -d, -f8)"
IMAGE_POST="$(echo $LINEA | cut -d, -f17 | sed "s|^./|$LINK/|")"
DATE="$(echo $LINEA | cut -d, -f4)"
HORA="$(echo $LINEA | cut -d, -f16)"
DATEPU="$(LANG=en_us_88591 ; date -d"$DATE" +'%a, %d %b %Y')"
DATEPUB=$(echo "$DATEPU $HORA +0100")
LANG=locale
GUID="http://ugeek.github.io"
echo "   <item>" >> $WORD.xml
echo "    <title>$TITLE_F</title>" >> $WORD.xml
echo "    <link>$LINK/post/$DATE-$LINK_P.html</link>" >> $WORD.xml
echo "    <description>" >> $WORD.xml
echo '&lt;img src="'$IMAGE_POST'" alt="'$TITLE_F'"&gt;'   >> $WORD.xml
echo "&lt;br&gt;&lt;p&gt;$DESC... 
&lt;p&gt;Sigue leyendo el post completo de &lt;a href="$LINK/post/$DATE-$LINK_P.html"&gt;$TITLE_F&lt;/a&gt;

&lt;/a&gt;&lt;/p&gt;&lt;p&gt;

&lt;a href="$LINK"&gt;Visita $TITLE&lt;/a&gt;

&lt;/a&gt;&lt;/p&gt;&lt;p&gt;

&lt;a href="https://ugeek.github.io"&gt;Visita uGeek Podcast&lt;/a&gt;


&lt;/a&gt;&lt;/p&gt;&lt;p&gt;

&lt;a href="http://feeds.feedburner.com/ugeekblog"&gt;Suscribete al Blog de uGeek&lt;/a&gt;

&lt;/a&gt;&lt;/p&gt;&lt;p&gt;

&lt;a href="http://feeds.feedburner.com/ugeek"&gt;Suscribete al Podcast de uGeek&lt;/a&gt;

</description>" >> $WORD.xml
echo "    <pubDate>$DATEPUB</pubDate>" >> $WORD.xml
echo '    <category>'$CATEGORY_POST'</category>'  >> $WORD.xml
echo '    <category>'$CATEGORY_POST1'</category>'  >> $WORD.xml
echo '    <category>'$CATEGORY_POST2'</category>'  >> $WORD.xml
echo '    <category>'$CATEGORY_POST3'</category>'  >> $WORD.xml
echo "    <guid>$LINK/post/$DATE-$LINK_P.html</guid>
   </item>" >> $WORD.xml
done < emacs.csv
echo "  </channel>
</rss>" >> $WORD.xml
echo "Generando Página Home"
cat posts.csv | head -n5 > posts_home.csv
echo " " >> index.org
echo "$INDEX" >> index.org
echo " " >> index.org
echo "*** Últimos Artículos" >> index.org
echo " " >> index.org
while read LINEA; do 
TPOST=$(echo $LINEA | cut -d, -f1 | sed 's/|/,/g')
UPOST=$(echo $LINEA | cut -d, -f2)
DPOST=$(echo $LINEA | cut -d, -f4)
#echo "- /$DPOST/ - [[$LINK/post/$DPOST-$UPOST.html][$TPOST]] " >> index.org
echo "- [[$LINK/post/$DPOST-$UPOST.html][$TPOST]] " >> index.org
done < posts_home.csv
echo "$INDEX_NEXT" >> index.org
echo '<head>
<title>'$TITLE'</title>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<div id="logo"><a href="https://ugeek.github.io"><img src="./icon/ugeek.png" border="0"  width="90" height="90" alt="uGeek"></a></div>
<link rel="stylesheet" type="text/css" href="./css/stylesheet.css" /><link rel="alternate" type="application/rss+xml" href="https://ugeek.github.io/feed.xml" title="uGeek - Blog de Tecnología">

<meta name="twitter:site" content="'$TWITTER'" />
<meta name="twitter:card" content="summary_large_image" />
<link rel="alternate" type="application/rss+xml" title="uGeek. Blog de Tecnología" href="'$LINK'/feed/" />


<meta name="robots" content="index, follow">
<meta name="author" content="'$AUTHOR'">
<meta name="description" content="'$DESCRIPTION'" />

<link rel="shortcut icon" href="'$LINK$ICON'" type="image/x-icon" />
<link rel="icon" href="'$LINK$ICON'" sizes="32x32" />
<link rel="icon" href="'$LINK$ICON'" sizes="192x192" />
<link rel="apple-touch-icon-precomposed" href="'$LINK$ICON'" />
<meta property="og:locale" content="'$LANGUAGE'" />


<meta property="og:site_name" content="'$TITLE'"/> 
<meta property="og:title" content="'$TITLE'" />
<meta property="og:description" content="'$DESCRIPTION'" />
<meta property="og:image" content="'$IMAGE'" />
<meta property="og:url" content="'$LINK'index.html" />

<meta name="twitter:title" content="'$TITLE'" />
<meta name="twitter:description" content="'$DESCRIPTION'" />
<meta name="twitter:image" content="'$IMAGE'" />

<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id='$GOOGLE_ANALITYCS'"></script>
<script>
window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag("'js'", new Date())
gtag("'config'", "'$GOOGLE_ANALITYCS'");
</script>


</head>

<br><br><br><br><br><br><br><br><br>
'$HEAD_PAGE'
'> index.html
cat index.org | pandoc --from org --to html5 >> index.html
echo $ORG $PIE_WEB  >> index.html
sed -i 's|__icon/|icon/|g' index.html
sed -i 's|__css/|css/|g' index.html
rm index.org posts_home.csv
echo "Generando Lista de Artículos"
echo "* $NUM_POSTS Artículos Publicados" >> list.org
while read LINEA; do 
TPOST=$(echo $LINEA | cut -d, -f1 | sed 's/|/,/g')
UPOST=$(echo $LINEA | cut -d, -f2)
DPOST=$(echo $LINEA | cut -d, -f4)
echo "- /$DPOST/ - [[$LINK/post/$DPOST-$UPOST.html][$TPOST]] " >> list.org
done < posts.csv 
echo '<head>
<title>Artículos. '$TITLE'</title>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<div id="logo"><a href="https://ugeek.github.io"><img src="./icon/ugeek.png" border="0"  width="90" height="90" alt="uGeek"></a></div>
<link rel="stylesheet" type="text/css" href="./css/stylesheet.css" /><link rel="alternate" type="application/rss+xml" href="https://ugeek.github.io/feed.xml" title="uGeek - Blog de Tecnología">


<meta name="twitter:site" content="'$TWITTER'" />
<meta name="twitter:card" content="summary_large_image" />
<link rel="alternate" type="application/rss+xml" title="uGeek. Blog de Tecnología" href="'$LINK'/feed/" />

<meta name="robots" content="index, follow">
<meta name="author" content="'$AUTHOR'">
<meta name="description" content="'$DESCRIPTION'" />

<link rel="shortcut icon" href="'$LINK$ICON'" type="image/x-icon" />
<link rel="icon" href="'$LINK$ICON'" sizes="32x32" />
<link rel="icon" href="'$LINK$ICON'" sizes="192x192" />
<link rel="apple-touch-icon-precomposed" href="'$LINK$ICON'" />
<meta property="og:locale" content="'$LANGUAGE'" />


<meta property="og:site_name" content="'$TITLE'"/> 
<meta property="og:title" content="'$TITLE'" />
<meta property="og:description" content="'$DESCRIPTION'" />
<meta property="og:image" content="'$IMAGE'" />
<meta property="og:url" content="'$LINK'index.html" />

<meta name="twitter:title" content="'$TITLE'" />
<meta name="twitter:description" content="'$DESCRIPTION'" />
<meta name="twitter:image" content="'$IMAGE'" />

<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id='$GOOGLE_ANALITYCS'"></script>
<script>
window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag("'js'", new Date())
gtag("'config'", "'$GOOGLE_ANALITYCS'");
</script>


</head>

<br><br><br><br><br><br><br><br><br>

'$HEAD_PAGE'
' > list.html
cat list.org | pandoc --from org --to html5 >> list.html
echo $ORG $PIE_WEB  >> list.html
sed -i 's|__icon/|icon/|g' list.html
sed -i 's|__css/|css/|g' list.html
rm list.org
echo "Generando Clasificación por Tags"
echo "** Etiquetas" >> tag.org
echo " " >> tag.org
while read TAG; do 
grep -i "$TAG" posts.csv > temp_tag.csv
echo "*** $TAG" >> tag.org
NUM_TAGS=$(cat tag.csv | wc -l)
while read LINEA; do 
TPOST=$(echo $LINEA | cut -d, -f1 | sed 's/|/,/g' )
UPOST=$(echo $LINEA | cut -d, -f2)
DPOST=$(echo $LINEA | cut -d, -f4)
echo "- /$DPOST/ - [[$LINK/post/$DPOST-$UPOST.html][$TPOST]] " >> tag.org
done < temp_tag.csv
done < tag.csv 
rm temp_tag.csv
echo '<head>
<title>Etiquetas. '$TITLE'</title>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<div id="logo"><a href="https://ugeek.github.io"><img src="./icon/ugeek.png" border="0"  width="90" height="90" alt="uGeek"></a></div>
<link rel="stylesheet" type="text/css" href="./css/stylesheet.css" /><link rel="alternate" type="application/rss+xml" href="https://ugeek.github.io/feed.xml" title="uGeek - Blog de Tecnología">

<meta name="twitter:site" content="'$TWITTER'" />
<meta name="twitter:card" content="summary_large_image" />
<link rel="alternate" type="application/rss+xml" title="uGeek. Blog de Tecnología" href="'$LINK'/feed/" />


<meta name="robots" content="index, follow">
<meta name="author" content="'$AUTHOR'">
<meta name="description" content="'$DESCRIPTION'" />
 

<link rel="shortcut icon" href="'$LINK$ICON'" type="image/x-icon" />
<link rel="icon" href="'$LINK$ICON'" sizes="32x32" />
<link rel="icon" href="'$LINK$ICON'" sizes="192x192" />
<link rel="apple-touch-icon-precomposed" href="'$LINK$ICON'" />
<meta property="og:locale" content="'$LANGUAGE'" />


<meta property="og:site_name" content="'$TITLE'"/>
<meta property="og:title" content="'$TITLE'" />
<meta property="og:description" content="'$DESCRIPTION'" />
<meta property="og:image" content="'$IMAGE'" />
<meta property="og:url" content="'$LINK'index.html" />

<meta name="twitter:title" content="'$TITLE'" />
<meta name="twitter:description" content="'$DESCRIPTION'" />
<meta name="twitter:image" content="'$IMAGE'" />

<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id='$GOOGLE_ANALITYCS'"></script>
<script>
window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag("'js'", new Date())
gtag("'config'", "'$GOOGLE_ANALITYCS'");
</script>


</head>

<br><br><br><br><br><br><br><br><br>

'$HEAD_PAGE'
' > tag.html
cat tag.org | pandoc --from org --to html5 >> tag.html
echo $ORG $PIE_WEB  >> tag.html
sed -i 's|__icon/|icon/|g' tag.html
sed -i 's|__css/|css/|g' tag.html
rm tag.org category_temp_post.csv cat_temp.csv
rm *~ > /dev/null 2>&1
else
echo "No hay ningun Post con estado TODO"
fi
rm posts.csv emacs.csv
rm  posts4feed.csv postsID.csv 
rm tag.csv tags.csv tag temp_post.org
rm category.csv hour image
rm title link description category date date-  
sed -i '$d' $1
fi
fi
fi
fi
